development: 
    adapter: postgresql
    database: de0p4kut6c2m8s
    pool: 5
    timeout: 5000

test: 
    adapter: postgresql
    database: de0p4kut6c2m8s
    pool: 5000
    timeout: 5000
    
production: 
    adapter: postgresql
    database: de0p4kut6c2m8s
    pool: 5
    timeout: 5000
